In [1]:
print("hello world")

hello world


In [2]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [3]:
import pandas as pd


In [4]:
import numpy as np

In [5]:
import datetime

In [6]:
x= datetime.datetime.now()

In [7]:
print(x)

2024-05-15 15:14:29.050546


In [8]:
a=np.array([20,30,40])
b=np.array([80,70,60])

In [9]:
print(a)
print(b)
print(a+b)

[20 30 40]
[80 70 60]
[100 100 100]


In [10]:
a=np.array([40,50,'60'])
print(a)

['40' '50' '60']


In [13]:
print(a*b)


UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U11'), dtype('int32')) -> None

In [17]:
arr=np.array([10,20,30,40,50])
print(arr[0:3])
print(arr[:2])

[10 20 30]
[10 20]


In [ ]:
#insepceting array

In [20]:
#a.shape-array dimension
#len(a)
#b.ndim-number of array dimension
#e.size-number of array elements
#b.dtype-data type of array elements
#b.astype(int)-convert on array to a different type

In [29]:
a=[[30,40,50,60,10],[10,20,30,40,50]]
arr=np.array(a)
print(arr)
print(arr.shape)#rows,coloumns
print(len(a))#number of nested values
print(np.size(arr))#number of elements
print(type(arr))#datatype of the variable
print(arr.dtype)#datatype of array
print(arr.astype(int))#conversion of datatype

[[30 40 50 60 10]
 [10 20 30 40 50]]
(2, 5)
2
10
<class 'numpy.ndarray'>
int32


In [40]:
a=np.array([10,20])
b=np.array([40,30])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))
print(np.concatenate([a,b]))
print(np.append(a,[90,100]))
print(np.insert(a,0,[20]))#array ,index,value
print(np.delete(a,1))#will delete element on indx 1





[50 50]
[-30 -10]
[0.25       0.66666667]
[400 600]
[10 20 40 30]
[ 10  20  90 100]
[20 10 20]
[10]


In [49]:
a=np.array([1,5,6,2])
print(np.sort(a))

s=np.where(a==6)
print(s)
s=np.where(a%2==0)
print(s)

fa=[True,False,True,False]#jha true h bs vo print hua 
new=a[fa]
print(new)


print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.cumsum(a))
print(np.cumprod(a))

[1 2 5 6]
(array([2], dtype=int64),)
(array([2, 3], dtype=int64),)
[1 6]
14
1
6
3.5
[ 1  6 12 14]
[ 1  5 30 60]


In [54]:
#wscube tech
#stastical functions
import statistics as stats
baked_food=[200,300,150,130,200,280,170,188]


a=np.array(baked_food)
print(np.mean(baked_food))
print(np.median(baked_food))
print(stats.mode(baked_food))
print(np.std(baked_food))#standarad division to check quality control
print(np.var(baked_food))




202.25
194.0
200
55.68157235567257
3100.4375


In [55]:
#learning pandas

import pandas as pd
data={"name":["john","peter","lisa"],
     "age":[25,28,31],
     "salary":[300000,400000,500000]}
df=pd.DataFrame(data)
print(df)

    name  age  salary
0   john   25  300000
1  peter   28  400000
2   lisa   31  500000


In [58]:
# to import file 
data=pd.read_csv("C:/Users/kashish mishra/Downloads/hotel_bookings.csv")
print(data)

#to read excel file download library pip install openpyxl
#data=pd.read_excel("excel file path")


               hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July     

In [59]:
print(data.head())
print(data.tail())

          hotel  is_canceled  lead_time  arrival_date_year arrival_date_month  \
0  Resort Hotel            0        342               2015               July   
1  Resort Hotel            0        737               2015               July   
2  Resort Hotel            0          7               2015               July   
3  Resort Hotel            0         13               2015               July   
4  Resort Hotel            0         14               2015               July   

   arrival_date_week_number  arrival_date_day_of_month  \
0                        27                          1   
1                        27                          1   
2                        27                          1   
3                        27                          1   
4                        27                          1   

   stays_in_weekend_nights  stays_in_week_nights  adults  ...  deposit_type  \
0                        0                     0       2  ...    No Deposit   
1     

In [60]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   hotel                           119390 non-null  object 
 1   is_canceled                     119390 non-null  int64  
 2   lead_time                       119390 non-null  int64  
 3   arrival_date_year               119390 non-null  int64  
 4   arrival_date_month              119390 non-null  object 
 5   arrival_date_week_number        119390 non-null  int64  
 6   arrival_date_day_of_month       119390 non-null  int64  
 7   stays_in_weekend_nights         119390 non-null  int64  
 8   stays_in_week_nights            119390 non-null  int64  
 9   adults                          119390 non-null  int64  
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64  
 12  meal            

In [62]:
data.describe()

is_canceled      lead_time  arrival_date_year  \
count  119390.000000  119390.000000      119390.000000   
mean        0.370416     104.011416        2016.156554   
std         0.482918     106.863097           0.707476   
min         0.000000       0.000000        2015.000000   
25%         0.000000      18.000000        2016.000000   
50%         0.000000      69.000000        2016.000000   
75%         1.000000     160.000000        2017.000000   
max         1.000000     737.000000        2017.000000   

       arrival_date_week_number  arrival_date_day_of_month  \
count             119390.000000              119390.000000   
mean                  27.165173                  15.798241   
std                   13.605138                   8.780829   
min                    1.000000                   1.000000   
25%                   16.000000                   8.000000   
50%                   28.000000                  16.000000   
75%                   38.000000                  23.000000   
max                   53.000000                  31.000000   

       stays_in_weekend_nights  stays_in_week_nights         adults  \
count            119390.000000         119390.000000  119390.000000   
mean                  0.927599              2.500302       1.856403   
std                   0.998613              1.908286       0.579261   
min                   0.000000              0.000000       0.000000   
25%                   0.000000              1.000000       2.000000   
50%                   1.000000              2.000000       2.000000   
75%                   2.000000              3.000000       2.000000   
max                  19.000000             50.000000      55.000000   

            children         babies  is_repeated_guest  \
count  119386.000000  119390.000000      119390.000000   
mean        0.103890       0.007949           0.031912   
std         0.398561       0.097436           0.175767   
min         0.000000       0.000000           0.000000   
25%         0.000000       0.000000           0.000000   
50%         0.000000       0.000000           0.000000   
75%         0.000000       0.000000           0.000000   
max        10.000000      10.000000           1.000000   

       previous_cancellations  previous_bookings_not_canceled  \
count           119390.000000                   119390.000000   
mean                 0.087118                        0.137097   
std                  0.844336                        1.497437   
min                  0.000000                        0.000000   
25%                  0.000000                        0.000000   
50%                  0.000000                        0.000000   
75%                  0.000000                        0.000000   
max                 26.000000                       72.000000   

       booking_changes          agent      company  days_in_waiting_list  \
count    119390.000000  103050.000000  6797.000000         119390.000000   
mean          0.221124      86.693382   189.266735              2.321149   
std           0.652306     110.774548   131.655015             17.594721   
min           0.000000       1.000000     6.000000              0.000000   
25%           0.000000       9.000000    62.000000              0.000000   
50%           0.000000      14.000000   179.000000              0.000000   
75%           0.000000     229.000000   270.000000              0.000000   
max          21.000000     535.000000   543.000000            391.000000   

                 adr  required_car_parking_spaces  total_of_special_requests  
count  119390.000000                119390.000000              119390.000000  
mean      101.831122                     0.062518                   0.571363  
std        50.535790                     0.245291                   0.792798  
min        -6.380000                     0.000000                   0.000000  
25%        69.290000                     0.000000                   0.000000  
50%        94.57500

In [63]:
print(data.isnull().sum())

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [66]:
print(data["is_repeated_guest"].duplicated().sum)

<bound method NDFrame._add_numeric_operations.<locals>.sum of 0         False
1          True
2          True
3          True
4          True
          ...  
119385     True
119386     True
119387     True
119388     True
119389     True
Name: is_repeated_guest, Length: 119390, dtype: bool>


In [ ]:
#to drop duplicates data.drop_duplicates[coloumn_name] always use them for primary keys

In [67]:
#working with null values

print(data.isnull().sum())

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company         

In [68]:
print(data.dropna())

               hotel  is_canceled  lead_time  arrival_date_year  \
2392    Resort Hotel            0          6               2015   
2697    Resort Hotel            0         24               2015   
2867    Resort Hotel            0         24               2015   
2877    Resort Hotel            0         24               2015   
2878    Resort Hotel            0         24               2015   
...              ...          ...        ...                ...   
112499    City Hotel            0         13               2017   
113046    City Hotel            0         13               2017   
113082    City Hotel            0         13               2017   
113627    City Hotel            0        210               2017   
116451    City Hotel            0        191               2017   

       arrival_date_month  arrival_date_week_number  \
2392              October                        42   
2697              October                        44   
2867             November     

In [69]:
print(data.replace(np.nan,'sorry'))

               hotel  is_canceled  lead_time  arrival_date_year  \
0       Resort Hotel            0        342               2015   
1       Resort Hotel            0        737               2015   
2       Resort Hotel            0          7               2015   
3       Resort Hotel            0         13               2015   
4       Resort Hotel            0         14               2015   
...              ...          ...        ...                ...   
119385    City Hotel            0         23               2017   
119386    City Hotel            0        102               2017   
119387    City Hotel            0         34               2017   
119388    City Hotel            0        109               2017   
119389    City Hotel            0        205               2017   

       arrival_date_month  arrival_date_week_number  \
0                    July                        27   
1                    July                        27   
2                    July     